# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_comments', '0002_auto_20160419_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='_Tagulous_Comment_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='_tagulous_comment_tags',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='comment',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', initial='"Dar es Salaam", Amsterdam, Entebbe, Jinja, Kampala, Kigali, Mombosa, Nairobi', null=True, to='tunga_comments._Tagulous_Comment_tags'),
        ),
    ]
