# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 12:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_comments', '0002_auto_20160419_1817'),
        ('tunga_tasks', '0012_auto_20160527_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='_Tagulous_Milestone_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='_Tagulous_TaskUpdate_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('state', models.IntegerField(choices=[(0, 'Completed'), (1, 'Overdue'), (2, 'active'), (3, 'closed')], default=2)),
                ('description', models.TextField()),
                ('order', models.SmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tags', tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', initial='Kampala, Entebbe, Jinja, Nairobi, Mombosa, Dar es Salaam, Kigali, Amsterdam', to='tunga_tasks._Tagulous_Milestone_tags')),
            ],
        ),
        migrations.CreateModel(
            name='TaskMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunga_tasks.Milestone')),
            ],
        ),
        migrations.CreateModel(
            name='TaskUpdate',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tunga_comments.Comment')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tags', tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', initial='"Dar es Salaam", Amsterdam, Entebbe, Jinja, Kampala, Kigali, Mombosa, Nairobi', to='tunga_tasks._Tagulous_TaskUpdate_tags')),
            ],
            bases=('tunga_comments.comment', models.Model),
        ),
        migrations.AlterField(
            model_name='task',
            name='skills',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', initial='Kampala, Entebbe, Jinja, Nairobi, Mombosa, Dar es Salaam, Kigali, Amsterdam', to='tunga_profiles.Skill'),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_updates', to='tunga_tasks.Task'),
        ),
        migrations.AddField(
            model_name='taskmilestone',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunga_tasks.Task'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunga_tasks.Task'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='_tagulous_taskupdate_tags',
            unique_together=set([('slug',)]),
        ),
        migrations.AlterUniqueTogether(
            name='_tagulous_milestone_tags',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='task',
            name='milestones',
            field=models.ManyToManyField(blank=True, related_name='task_milestones', through='tunga_tasks.TaskMilestone', to='tunga_tasks.Milestone'),
        ),
    ]
