# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0013_auto_20160611_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='type',
            field=models.IntegerField(choices=[(1, 'interval'), (2, 'update'), (3, 'update_request')], default=2),
        ),
    ]
