# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0014_milestone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='update_sent',
            field=models.NullBooleanField(),
        ),
    ]
